AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS_Media_Service

  Sample SAM Template for AWS_Media_Service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  MediaServiceS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "media-service-${AWS::AccountId}-${AWS::Region}"

  MediaServiceGetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: media_service/
      Handler: service_handler.get_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
      Environment:
        Variables:
          BUCKET_NAME: !Ref MediaServiceS3Bucket
      Policies:
        S3CrudPolicy:
          BucketName: !Ref MediaServiceS3Bucket

  MediaServicePostFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: media_service/
      Handler: service_handler.post_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: post
      Environment:
        Variables:
          BUCKET_NAME: !Ref MediaServiceS3Bucket
      Policies:
        S3CrudPolicy:
          BucketName: !Ref MediaServiceS3Bucket

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MediaServiceApi:
    Description: "API Gateway endpoint URL for Prod stage for MediaService function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  MediaServiceGetFunction:
    Description: "Hello MediaServiceFunction Lambda Function ARN"
    Value: !GetAtt MediaServiceGetFunction.Arn
  MediaServicePostFunction:
    Description: "Hello MediaServiceFunction Lambda Function ARN"
    Value: !GetAtt MediaServicePostFunction.Arn
  MediaServiceS3Bucket:
    Description: "MediaServiceS3Bucket"
    Value: !Ref MediaServiceS3Bucket
